---
- name:  "gSnap: ensure folder"
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/gSnap/"
    state: directory

- name: "gSnap: copy config"
  ansible.builtin.copy:
    src: gnome-extensions-gSnap-layouts.json
    dest: "/home/{{ user }}/.config/gSnap/layouts.json"