---
- name: Ensure snapd is installed
  become: true
  become_user: root
  ansible.builtin.apt:
    name: snapd
    state: present

- name: Ensure snapd is running
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: true

- name: Install Firefox via Snap
  community.general.snap:
    name: firefox
    state: present
  become: true
  become_user: root

- name: Install Chromium via Snap
  community.general.snap:
    name: chromium
    state: present
  become: true
  become_user: root
