---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew 
  register: homebrew_check

- name: Installing Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    - not homebrew_check.stat.exists

- name: "Ensure homebrew sourced in zsh"
  lineinfile:
    path: ~/.zshrc
    regexp:
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present
  
- name: "Ensure homebrew sourced in bash"
  lineinfile:
    path: ~/.bashrc
    regexp:
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present