---

- name: "Remmina: add repo"
  become: true #needed
  become_user: root
  ansible.builtin.apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next

- name: "Remmina: install"
  become: true #needed
  become_user: root
  apt:
    name: remmina

- name: "Remmina: remmina-plugin-rdp"
  become: true #needed
  become_user: root
  apt:
    name: remmina-plugin-rdp

- name: "Remmina: remmina-plugin-secret"
  become: true #needed
  become_user: root
  apt:
    name: remmina-plugin-secret
