---
- name: "Sublime: Install GPG key for"
  become: true #needed
  become_user: root
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: "Sublime:  add repo"
  become: true #needed
  become_user: root
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime

- name: "Sublime: Install"
  become: true #needed
  become_user: root
  package:
    name: '{{item.name}}'
    state: latest
  with_items:
    - { name: 'sublime-text' }